### ISSUE TITLE
Smudge Tool bug: Can't undo smudges.

### ISSUE THREAD

**Issue by Trolltass** [pencil2d/pencil#1004]
If I use the smudge tool i can't undo it. Very annoying :(

**Comment by Jose-Moreno** [comment]
@Trolltass Hi. Yes the smudge tool is a work in progress so don't use it for now. If you need that kind of effect use krita or GIMP to smudge the drawings and bring them back into pencil2D. You can copy paste back and forth between pencil2d and Krita without issues, haven't tried GIMP though.

Also this bug has been reported before, so we kindly ask that next time use the search function to see if the problem you have has already been reported. 

Developers are looking to integrate a library that allows better use of brushes so the smudge tool will only be improved once this library becomes integrated, we hope that will happen before summer 2019, but I can't give you an ETA since we're all volunteers and work time depends on our own schedules.

**Comment by Kaikogf** [comment]
@Jose-Moreno 
This issue is already fixed (it is working fine with the last code from 14th of Jun)  👍

**Comment by Jose-Moreno** [comment]
@Kaikogf I don't know exactly what is fixed for you, however I'm using June 17th nightly and I still can't undo neither smudge nor blur by using shortcuts or the menu action commands.

Are you sure you're not using the MyPaint version instead? 🤔 

I'm sorry to say that this issue will only be potentially fixed once @CandyFace implements the Undo/Redo system he was working on before actively developing the MyPaint branch 🖌️

**Comment by Kaikogf** [comment]
@Jose-Moreno 
I build the last code from June 17th .
In the video I used the shortcut for the smudge feature



![smudge](https://user-images.githubusercontent.com/28032931/85652561-04857100-b6a3-11ea-9135-e9add35e8b5a.gif)

**Comment by Kaikogf** [comment]
More than words 
👍 


![smudge](https://user-images.githubusercontent.com/28032931/85652887-d8b6bb00-b6a3-11ea-8c57-5c6214f25a6a.gif)

Using the shortcut for the smudge tool. Built the last code from jun 17th

**Comment by Jose-Moreno** [comment]
@Kaikogf Sorry it took me so long. Ok It seems that to me it works half way. What happens is:
1. I create a single brush stroke
2. Use the smudge tool
3. Undo -> In here the program undoes the operation but visually I still see the smudge
4. I undo again and the stroke is undone along the smudge (+ white artifacts)
5. I redo once and the stroke is redone with the smudge (+white artifacts)

It seems that the smudge tool events are getting merged with the drawing tool first stroke, after that you can smudge and undo just like your GIF. So **there's still a bug due to unwanted behavior** as I expect each smudge stroke to be acknowledged as an independent stroke in order to be undone.

This will be fixed with the new undo/redo system once CandyFace finalizes the finishing touches and includes the new features that require undo/redo, so I recommend not closing this just yet.
