### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by SANSYBOY1234** [pencil2d/pencil#581]
Ok so i am making animations with over 240 frames i save it and the next day i come and try to open it and it bugs out giving me a warning so now i cant open it and im mad i lost all that progress someone help me

**Comment by SANSYBOY1234** [comment]
is there more timeline room because i can only go to 240 frames...

**Comment by Jose-Moreno** [comment]
@SANSYBOY1234 Hi, sorry to hear you're having issues.

Usually for these reports it’s useful if you could tell us which version you are using and Which Operating system you have installed.

For most purposes if you’re using the old Pencil 0.5.4b version and you’re having lots of bugs please use the latest development update appropriate for your computer to see if they are already solved. You can find the download here:

https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM?usp=sharing#list

As for a possible solution to this issue:

1) Open Pencil2D (the newer version if possible)
2) Go to Edit > Preferences > Timeline > Timeline size in Frames 
3) Set the timeline size to a sensible number above your own frame count, like 500.
4) Try to open your file

If you still can't open your file after you try out these steps, then I'd have to ask you to zip both your .PCL file and the .data folder associated with it (which contains the elements and drawings). They can be found on the same directory where you saved the pencil2d file. Upload it to mega, mediafire or something and then post the link back here.

**Comment by SANSYBOY1234** [comment]
i still cant open my other animation but thanks for the timeline help...

**Comment by CandyFace** [comment]
The amount of information in this issue, makes it hard to diagnose. I'm closing the issue.

@SANSYBOY1234 if you still have this problem in the newest nightly build, please make a new issue and fill in as much information as possible.
