### ISSUE TITLE
Any Wordpress things to update ?

### ISSUE THREAD

**Issue by gordielachance** [pencil2d/pencil#825]
Please note here what I have to update on the current website (download links, etc); i'll do it today.
Thanks !

**Comment by J5lx** [comment]
Our IRC channel has changed from ##pencil2d to #pencil2d (with only one #), that should be updated in the main menu and the sidebar.

**Comment by gordielachance** [comment]
done!

**Comment by Jose-Moreno** [comment]
@gordielachance Hey, mostly the links to Discord, IRC (as K5lx commented), I opened a Facebook Group to "hold" people from the fanpage so we can announce things in a better way, but I'm still allowing it to get people organically. Other than that I think the wordpress plugin was asking for updates when I entered the panel a few months back, but I don't know if you already took care of that :smile: 

One thing I wanted to ask. Did you open the **twitter** account in here: https://twitter.com/pencil2d
If so, would you mind letting me handle it as well? Now facebook has a twitter cross-post functionality, and I'm a lot on twitter now and a lot of artitsts are on twitter, so I want to help spread our communications impact because right now Facebook and Tumblr are mostly what have kept the people flowing but it's hard to get by with just that.

**Comment by gordielachance** [comment]
Hi @Jose-Moreno, yes I can give you the credential to the Gmail and Twitter account.
What is your email ?

**Comment by Jose-Moreno** [comment]
@gordielachance Hey!, well I didn't know there was a gmail account, we created a new one for the youtube channel, if it's ok can you send the credentials to pencil2danimation (at) gmail.com ? If you want I can also create a drive document to have the shared credentials available for you as well. Thanks a lot :smile:

**Comment by J5lx** [comment]
@gordielachance You missed the sidebar. But I can’t blame you since I almost missed it, too :p

**Comment by gordielachance** [comment]
:) indeed... done !

2017-12-04 20:48 GMT+01:00 Jakob Gahde <notifications@github.com>:

**Comment by gordielachance** [comment]
@Jose-Moreno : I sent you the credentials !

**Comment by gordielachance** [comment]
@J5lx @Jose-Moreno : I just sent a copy of the Wordpress database to pencil2danimation (at) gmail.com.

**Comment by Jose-Moreno** [comment]
@gordielachance Thanks a lot! I'll share the database to J5lx so he can review how to implement that on discourse. I'll make sure to help with the twitter platform soon enough :smile:

**Comment by J5lx** [comment]
Closing due to https://github.com/pencil2d/pencil/issues/558#issuecomment-364582996 (aka the Wordpress site has been replaced by Discourse+Github Pages). Further issues about the website are probably best sent to [pencil2d/pencil2d.github.io](/pencil2d/pencil2d.github.io) and <https://discuss.pencil2d.org/c/site> or maybe #558.
